### ISSUE TITLE
Numbers displayed incorrectly in the order book

### ISSUE THREAD

**Issue by kirkyb** [XRPL-Labs/offer-create-xapp#11]
2 issues:

1) Decimal places aren't consistent when comparing buy / sell orders
2) Strange decimal place / comma behavior

See the attached images for reference.
![1624744596315](https://user-images.githubusercontent.com/30548482/123526833-628fce80-d6d2-11eb-8b57-9c8ac466447e.jpg)
![1624744596309](https://user-images.githubusercontent.com/30548482/123526835-658abf00-d6d2-11eb-808d-b92edcae1617.jpg)

**Comment by KoenPaas** [comment]
I've noticed it, thank you for the report, will work on it soon

**Comment by KoenPaas** [comment]
Fixed the issue with thousand separators. Significance fix is WIP

**Comment by kirkyb** [comment]
Thanks for the feedback Koen 👍

**Comment by KoenPaas** [comment]
Fixed
