### ISSUE TITLE
Market buy: buys more than intended (likely not a bug)

### ISSUE THREAD

**Issue by CodeWardNinja** [XRPL-Labs/offer-create-xapp#2]
When market buying a set amount of CSC, the quote is given, but if the order is filled for less than quoted, user receives more that requested to buy.

E.g.: 
I set market buy order on CSC/XRP pair at 100 CSC for 0.565 XRP (0.00565..), the order was filled for 0.54 XRP (0.0054) which resulted in receiving 103.06 CSC.

TX: 9B3AF19A541C1485A56FEC15A28283296FE53769C8FFDB5FFE7AB4B04A10A5BD

This also happens on the sell side, where if I market sell 100 CSC for quoted 0.565 XRP (0.00565..), the order fills for 0.55 XRP, resulting in getting less XRP than what was quoted. (hard to replicate sell side with limited liquidity/fillOrKill fails).

Again this isn't technically a bug in my opinion, just something to be aware of, as there's always a bit of slippage with market orders.

**Comment by KoenPaas** [comment]
A market order is technically not possible on the XRPL right now.
The market order is defined as:  _"A market order is an instruction by an investor to a broker to buy or sell stock shares, bonds, or other assets at the best available price in the current financial market."_ https://www.investopedia.com/terms/m/marketorder.asp

We had 3 options: 
1. Set a limit order with a price so low that it will "always" fill (if there's enough liquidity), practically a market order however this is confusing for users and therfore need to hide the Limit price.
2. Set a limit order exactly to the current market order, this will most likely never fill the order
3. Set a limit order increased/decreased according by a fixed percentage (cushion, currently at 5%.) to the market price.

We implemented the last option realistically the better way, that is why there's such a significant difference in what you received and paid.

What is your take on it?

**Comment by CodeWardNinja** [comment]
Hey Koen,

Sorry I didn't get a notification for this for some reason, but that makes sense.
As I mentioned it's likely not a bug, just something I noticed and figured to post on here as someone who may "market sell" in the xApp may see they got less than what they were selling for. However your explanation above makes sense.
