### ISSUE TITLE
Non-XRP asset faucets?

### ISSUE THREAD

**Issue by kirkyb** [XRPL-Labs/offer-create-xapp#3]
Are there any non-XRP faucets available for using the xApp on the testnet?

There are a number of XRP sell offers but it appears that nobody can fill them with the other assets.

**Comment by WietseWind** [comment]
Simply issue your own :)? https://xumm.community/tokens

**Comment by KoenPaas** [comment]
Would be great to have a tool that will let you make test trades on the DEX testnet, however not in the scope of this repo.
