### ISSUE TITLE
Get info not working

### ISSUE THREAD

**Issue by CodeWardNinja** [XRPL-Labs/offer-create-xapp#4]
After placing a limit order, the order shows in Open Orders.
Tapping the "Get Info" button isn't working (Cancel order works fine).

Device Specs:
Galaxy S9
Android Version 10
XUMM Version 2.0.2.3165731

![DEXxApp_GetTradeInfo](https://user-images.githubusercontent.com/22016837/122612896-ece08e80-d051-11eb-9a70-6727741024ad.jpg)

**Comment by kirkyb** [comment]
I have reproduced this and can confirm the same result.

Poco X3 Pro
Android 11

**Comment by KoenPaas** [comment]
This button will work with a future update of XUMM, the button should be dissabled if the XUMM version does not support the external link opening feature.

**Comment by KoenPaas** [comment]
Added an error message if XUMM version is below 2.1.0 (Next Update)
