### ISSUE TITLE
Asset amount after setting limit order

### ISSUE THREAD

**Issue by kirkyb** [XRPL-Labs/offer-create-xapp#5]
I don't know if this is necessarily an issue.
I've noticed that after placing a CSC limit sell order the DEX still shows my full amount as available for trading.

Is this normal behaviour or should it display 'total - outstanding orders' ?

**Comment by kirkyb** [comment]
Just following up on this.
Using the testnet I've just placed multiple sell orders  using the same quantity of XRP and it still shows that I have XRP available for trading.

**Comment by WietseWind** [comment]
That's correct, that's XRPL default behaviour. The XRPL allows you to "overcommit" selling: if you're out of the asset sold the remaining offers simply won't fill.
