### ISSUE TITLE
Order book issue

### ISSUE THREAD

**Issue by kirkyb** [XRPL-Labs/offer-create-xapp#7]
Using the testnet, XRP and my issued KirKoin.
I placed a buy offer and a sell offer so that neither were filled.
After successfully cancelling both orders I noticed that both are still visible in the order book.

**Comment by WietseWind** [comment]
Did you manually check your account lines to see if the offers are really gone? And did you try to force quit XUMM and open the xApp again to see if the xAPp still lists them?

**Comment by kirkyb** [comment]
Restarting XUMM fixes this issue. I have repeated the steps and can confirm that I observed the same behavior.
It's a confusing visual 'glitch', but good to know that the cancel offer took place.

**Comment by WietseWind** [comment]
OK, so then the remaining question is: would restarting the xApp do the trick as well (opposed to force quitting XUMM altogether)?

**Comment by kirkyb** [comment]
Restarting the xApp does indeed do the trick.
One thing I've noticed today is that the buy orders aren't being displayed (see attached)
![1624314979439](https://user-images.githubusercontent.com/30548482/122836282-dbb1af00-d2e9-11eb-98cf-d81d6f6b90be.jpg)

**Comment by WietseWind** [comment]
See #8 & #6  - same issue; caching / not updating list
