### ISSUE TITLE
Strange behavior when buying/selling 'own orders'

### ISSUE THREAD

**Issue by kirkyb** [XRPL-Labs/offer-create-xapp#8]
Some observations when buying / selling my own orders (i.e. this may not happen with 'normal' trading).

1) Create sell order.
2) Create buy order at same price and quantity.
3) Buy order clears, but sell remains. Both remain in the open orders section.
4) Restart xApp.
5) Order book is now clear, but buy order still remains in open orders.
6) Buy order is cancelled, but remains visible.
7) xApp is restarted and everything is now cleared.

https://user-images.githubusercontent.com/30548482/122838743-9d6abe80-d2ee-11eb-8a28-dcf910d59443.mp4

**Comment by WietseWind** [comment]
I'm going to refer to this report in one of the other ones and close some of them, so we have all related/similar issues in one issue. Thanks for reporting!
